In [19]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("./data", one_hot=True)

Extracting ./data/train-images-idx3-ubyte.gz
Extracting ./data/train-labels-idx1-ubyte.gz
Extracting ./data/t10k-images-idx3-ubyte.gz
Extracting ./data/t10k-labels-idx1-ubyte.gz


In [12]:
for _ in range(10000):
    batch_images, batch_labels = mnist.train.next_batch(100)
    batch_images_val, batch_labels_val = mnist.validation.next_batch(100)

In [13]:
model_inputs = tf.placeholder(dtype = tf.float32, shape= [None, 784])
labels = tf.placeholder(dtype=tf.float32, shape=[None, 10])

w = tf.Variable(tf.random_normal(shape=[784, 10]))
b = tf.Variable(tf.random_normal(shape=[10]))

In [28]:
logits = tf.matmul(model_inputs, w) + b
predictions = tf.nn.softmax(logits)

loss = tf.losses.softmax_cross_entropy(
    onehot_labels=labels,
    logits = predictions)

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)
train_op = optimizer.minimize(loss)

In [29]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(1000):
        batch_images, batch_labels = mnist.train.next_batch(100)
        feed = {model_inputs: batch_images, labels: batch_labels}
        _, loss_val = sess.run([train_op, loss], feed_dict=feed)
        print "step{}|loss:{}". format(step, loss_val)

step0|loss:2.3053483963
step1|loss:2.32930660248
step2|loss:2.35333657265
step3|loss:2.39154887199
step4|loss:2.3458096981
step5|loss:2.36332392693
step6|loss:2.35205364227
step7|loss:2.36314344406
step8|loss:2.36785030365
step9|loss:2.33226680756
step10|loss:2.33829402924
step11|loss:2.31362724304
step12|loss:2.33773446083
step13|loss:2.33018136024
step14|loss:2.31500315666
step15|loss:2.35906147957
step16|loss:2.33001804352
step17|loss:2.33820176125
step18|loss:2.38957738876
step19|loss:2.33003759384
step20|loss:2.37053656578
step21|loss:2.30635070801
step22|loss:2.34291815758
step23|loss:2.34435939789
step24|loss:2.35816407204
step25|loss:2.32020282745
step26|loss:2.36891913414
step27|loss:2.34672927856
step28|loss:2.31363749504
step29|loss:2.35866451263
step30|loss:2.32301998138
step31|loss:2.33606910706
step32|loss:2.36118364334
step33|loss:2.3268904686
step34|loss:2.34356546402
step35|loss:2.29547762871
step36|loss:2.31981992722
step37|loss:2.33137106895
step38|loss:2.30806398392

step335|loss:2.15376186371
step336|loss:2.1372461319
step337|loss:2.18243646622
step338|loss:2.10415554047
step339|loss:2.18438601494
step340|loss:2.08727622032
step341|loss:2.10804653168
step342|loss:2.10149931908
step343|loss:2.16476964951
step344|loss:2.11212992668
step345|loss:2.06299591064
step346|loss:2.13954257965
step347|loss:2.15489053726
step348|loss:2.1257879734
step349|loss:2.06778216362
step350|loss:2.05779743195
step351|loss:2.10533738136
step352|loss:2.1078209877
step353|loss:2.13629221916
step354|loss:2.14378428459
step355|loss:2.13492393494
step356|loss:2.11650300026
step357|loss:2.12502098083
step358|loss:2.1711397171
step359|loss:2.11391758919
step360|loss:2.13901019096
step361|loss:2.07097625732
step362|loss:2.11045026779
step363|loss:2.12128901482
step364|loss:2.06487560272
step365|loss:2.10054755211
step366|loss:2.083537817
step367|loss:2.09038329124
step368|loss:2.09138393402
step369|loss:2.13404273987
step370|loss:2.18388342857
step371|loss:2.11108875275
step372

step723|loss:1.90637528896
step724|loss:1.83630096912
step725|loss:1.92433619499
step726|loss:1.90557134151
step727|loss:1.98246586323
step728|loss:1.99784839153
step729|loss:1.84937870502
step730|loss:1.8763166666
step731|loss:1.93473255634
step732|loss:1.94834136963
step733|loss:2.00678539276
step734|loss:2.02425861359
step735|loss:1.98182499409
step736|loss:2.03591227531
step737|loss:1.98489058018
step738|loss:2.01133537292
step739|loss:1.91976618767
step740|loss:1.87144052982
step741|loss:1.93358886242
step742|loss:1.9317971468
step743|loss:1.98493075371
step744|loss:1.92113351822
step745|loss:1.89887392521
step746|loss:1.91369509697
step747|loss:1.89878845215
step748|loss:1.94158542156
step749|loss:1.87395739555
step750|loss:1.911454916
step751|loss:1.92512583733
step752|loss:1.92478775978
step753|loss:1.91604852676
step754|loss:1.95443272591
step755|loss:1.96853256226
step756|loss:1.97019541264
step757|loss:1.90578019619
step758|loss:2.00761127472
step759|loss:1.94503855705
step7

In [22]:
a = np.zeros((10, 10))
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [24]:
print a
print b
print a+b

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[ 1  2  3  4  5  6  7  8  9 10]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]


In [30]:
from tensorflow import flags
FLAGS = flags.FLAGS

flags.DEFINE_integer("batch_size", 128, "number of batch size. default 128.")
flags.DEFINE_float("learning_rate", 0.01, "initial learning rate.")
flags.DEFINE_integer("max_steps", 10000, "max steps to train.")

In [31]:
batch_size = FLAGS.batch_size
learning_rate = FLAGS.learning_rate
max_step = FLAGS.max_steps

In [33]:
import tensorflow as tf
a = tf.Variable(tf.random_normal(shape=[10]))
b = tf.Variable(tf.zeros(shape=[10]))
print a.name
print b.name

Variable_4:0
Variable_5:0


In [36]:
c = tf.Variable(tf.ones(shape=[10]), name="my_variable")
d = tf.Variable(tf.zeros(shape=[]), name = "my_variable")

In [37]:
print c.name
print d.name

my_variable_2:0
my_variable_3:0


In [44]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(d)

0.0

In [48]:
import tensorflow as tf
a = tf.Variable(tf.random_normal(shape=[10]))
b = tf.Variable(tf.random_normal(shape=[5]))
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    save_path = saver.save(sess, "./logs/model.ckpt")
    print sess.run(a)
    print sess.run(b)

[ 0.49142015  1.26428437  1.12334168  0.2463512  -0.09817197  1.15233934
  1.07859254  1.14460909 -0.95934194  0.94209266]
[-0.48822218  1.00148344  0.25159547  0.20015268 -0.0788374 ]
